### ISSUE TITLE
Question about OSC terror phases

### ISSUE THREAD

**Issue by YOUNGBLOOD428** [ChrisFeline/ToNSaveManager#102]
Having some trouble understanding how the phase indication in OSC works (partly due to terrors not giving one with phases)

Is it 0 for no phases, and 1 for if it has phases plus further phases, or does it work differently?

(Mostly asking about the first terror, but if the other two terrors display differently let me know)

**Comment by ChrisFeline** [comment]
Is for Faker and Bliss, it is >0 when transformed.

**Comment by YOUNGBLOOD428** [comment]
Ah, so to confirm, if it was sonic for example, it starts on 0, but when he becomes faker, it becomes 1?

**Comment by ChrisFeline** [comment]
Yes

**Comment by YOUNGBLOOD428** [comment]
Alright, this should help, thanks for your time!
