### ISSUE TITLE
using Line Break code in js tag causes the js tag stop working

### ISSUE THREAD

**Issue by Assault1892** [ChrisFeline/ToNSaveManager#103]
use <js> tag in a OSC Send Chatbox Message and use the line break code `\n` in the message, the js tag will not work properly.

https://github.com/user-attachments/assets/0217b3c9-183a-4cfb-bfea-5462f4db0e3d

**Comment by ChrisFeline** [comment]
I made a test build with this change here: https://github.com/ChrisFeline/ToNSaveManager/actions/runs/12331843142
Would you try it and if so, let me know if it does the intended effect.

**Comment by Assault1892** [comment]
it's fixed, thanks!!

https://github.com/user-attachments/assets/74978ddd-ab44-4c7c-bff5-8310ed35ae54
