### ISSUE TITLE
About the parameters of the round "Cold Night"

### ISSUE THREAD

**Issue by IO0707** [ChrisFeline/ToNSaveManager#106]
The round type parameter returned at the start of a “cold night” is probably set to 0.
The round name is also listed as “Intermission” in the Save Manager.
Please check if you would like to confirm this.

「ラウンドタイプ : 休憩時間」=「Round Type : Intermission」
![スクリーンショット (920)](https://github.com/user-attachments/assets/5e184af6-5064-436f-a7c6-d2f2c5b09763)

**Comment by ChrisFeline** [comment]
Seems like the name for Cold Night changed to `コールドナイト` internally for JP. I might be able to fix this next update.

**Comment by IO0707** [comment]
Thank you for your reply.
I would appreciate it if you could also check the parameters just to be sure, as the “ToN_RoundType” value seemed to be 0 when I checked it on the OSC debugging board.

**Comment by ChrisFeline** [comment]
I would need a log file with a Cold Night round encounter to properly test this out.

**Comment by IO0707** [comment]
I encountered this about 3 hours ago and can provide the log file.
How do I give it to you?

**Comment by ChrisFeline** [comment]
You can join the discord found in the README.md of this repo, then you can message me directly on there.

**Comment by IO0707** [comment]
I joined the dicord server.
Is it OK if I send you the text file of the log by DM?

**Comment by ChrisFeline** [comment]
Yeah, DMs are okay.

**Comment by ChrisFeline** [comment]
Feel free to open this issue again if this problem still persists.
