### ISSUE TITLE
Save Manager Fails to Copy Code to Clipboard When "Copy On Join" is Enabled

### ISSUE THREAD

**Issue by SalbugVR** [ChrisFeline/ToNSaveManager#109]
Despite having `Copy On Join` enabled, the Save Manager does not automatically copy the latest code to the clipboard upon joining a new instance.

![image](https://github.com/user-attachments/assets/f9d7fccf-0fef-4df7-b937-7839dd98afe8)

**Comment by ChrisFeline** [comment]
AAAAAAAAAAAAAAAAA

**Comment by ChrisFeline** [comment]
There's an artifact build that implements a fix for this.
I would appreciate if you could test if these are working properly again:
https://github.com/ChrisFeline/ToNSaveManager/actions/runs/12534407066

**Comment by SalbugVR** [comment]
Testing confirms that the fixes on the artifact build are working as intended.
