### ISSUE TITLE
Left panel date can get cutoff

### ISSUE THREAD

**Issue by Tran-Foxxo** [ChrisFeline/ToNSaveManager#21]
Having `24 Hour Time` disabled and `Show Seconds` enabled causes the date and time in the left panel to be cutoff.

![image](https://github.com/ChrisFeline/ToNSaveManager/assets/22718078/9fe0b90b-1458-4025-9fad-aba61e243915)

**Comment by ChrisFeline** [comment]
Last update added a Window Splitter, you can now readjust the left panel window and change it's size.
