### ISSUE TITLE
The save manager seem to not find my logs

### ISSUE THREAD

**Issue by YshaOnGit** [ChrisFeline/ToNSaveManager#25]
I've installed the save manager 2 days ago, when first launch the two place where logs and save should be are empty, even after playing a full night it seem to not get new codes
I have no idea what could cause that (Or if I've done something wrong)
![image_2024-01-04_040303177](https://github.com/ChrisFeline/ToNSaveManager/assets/155600934/cf0645f0-5a25-4f19-a0ef-7121c99e971e)

**Comment by ChrisFeline** [comment]
Do you have logging enabled in your VRChat menu?
![logging](https://github.com/ChrisFeline/ToNSaveManager/assets/41535779/814d59af-42ad-41eb-a87d-265cb562a05e)

**Comment by YshaOnGit** [comment]
I was turn off indeed, thanks now it's working !
I didn't even knew that was an option
