### ISSUE TITLE
Localization: Add additional keys for round-tag abbreviations

### ISSUE THREAD

**Issue by sageyx2002** [ChrisFeline/ToNSaveManager#46]
Hey there!

While creating the German locale, I noticed these two lines and thought I'd open a quick issue on this:

https://github.com/ChrisFeline/ToNSaveManager/blob/4ab3d6cff2ecc2ccd6b1b99f2333fa50c866d2ff/Localization/Language/en-US.json#L77-L78

I'd like to suggest adding some additional keys to allow for locale-specific replacement of these tags. My assumption is that these tags are referring to the English words "Respawn"/"Respawned", "Win"/"Won", and "Death"/"Died". Other languages might use different abbreviations, which can make these harder to interpret.

Additionally, adding a line to the tooltip on Line 78 might be useful, to explain what the abbreviations refer to. While I'm no expert on other languages, I believe the Japanese translation could use a single Kanji character in place as well, which might make it even more intuitive.

**Comment by ChrisFeline** [comment]
I will consider it

**Comment by ChrisFeline** [comment]
The reason I haven't addressed this issue yet is because the tags are [hardcoded into an enumerator](https://github.com/ChrisFeline/ToNSaveManager/blob/4ab3d6cff2ecc2ccd6b1b99f2333fa50c866d2ff/Models/ToNIndex.cs#L154). Really a bad decision on my side.

I have tried using emojis on windows forms with the current font I've been using and it looks like this:
![image](https://github.com/user-attachments/assets/078d3b37-02bd-49db-9596-7accff8ef4d1)
Do you think this looks good enough? If so I will proceed to replace the tags and add a more descriptive tool tip for the control.

For example:
`"SETTINGS.SHOWWINLOSE.TT": "Entries will show a tag based on the source that triggered the save.\n🔄 Respawned.\n🏆 Survived.\n🔌 Disconnected.",`

**Comment by sageyx2002** [comment]
That looks great on my end, good idea from nomlasvrc!
I already updated my fork, made minor adjustments to it, as well as adding the line you provided preemptively, can update that prior to sending a pull request should you wish to change it 😃

**Comment by ChrisFeline** [comment]
@sageyx2002 
That commit will not change the tool tip, it will change the whole label for the toggle.
The example is still just an idea, I am working internally on how to implement this in a way that works for me and everyone.
Also the next update will take some time, as it will be released with the next version of ToN. So, there will be a lot of translation changes and additions.

**Comment by sageyx2002** [comment]
Got it! Going to keep that in mind.

**Comment by ChrisFeline** [comment]
Alright, I implemented this request. But please wait before updating your strings.
There will be 3 new keys:
```json
"SAVE.TAG_R": "🔄",
"SAVE.TAG_W": "🏆",
"SAVE.TAG_D": "🔌",
```
> These might change on release, but not worries.

These will most likely not need a translation, as this is pretty much globally visible.
There's a bit of a downside, I can't add these to the information in the settings window as they show as question marks. So instead I've changed the text and the context for the toggle label that enables this feature:
![image](https://github.com/user-attachments/assets/cc587736-df3a-478e-a267-989674037b89)

The tooltip for this entry will also change:
```json
"SETTINGS.SHOWWINLOSE.TT": "Entries will show a tag based on the source that triggered the save.\n$$SAVE.TAG_R$$ Respawned.\n$$SAVE.TAG_W$$ Survived.\n$$SAVE.TAG_D$$ Disconnected.",
```

Note that this tooltip has string templates that inherit content from other keys.
`$$SAVE.TAG_R$$`

Thank you for your suggestions, hope this will be enough.

**Comment by sageyx2002** [comment]
Absolutely! This is great!
I was a bit fast on that commit, and I will wait before updating. Thank you for the quick update!

**Comment by nomlasvrc** [comment]
Thank you for adopting my idea! I am relieved that the pictograms are displayed correctly.
I added the Japanese translation of that tooltip in a separate branch.

**Comment by ChrisFeline** [comment]
Added on latest TON update.
