### ISSUE TITLE
Application not responding after update

### ISSUE THREAD

**Issue by inkuxuan** [ChrisFeline/ToNSaveManager#53]
After updating to Release 2024.10.4.144, the application hangs on start.

![image](https://github.com/user-attachments/assets/54b3abfc-2e3c-469c-b82c-ffe9fa501813)

output.log only contains initializations and instance logs which are all INFO level.
```
2024.10.04 23:42:21 INFO       -  Selecting language key: en-US
2024.10.04 23:42:22 INFO       -  Searching language key...
2024.10.04 23:42:22 INFO       -  Current UI Language Info:
2024.10.04 23:42:22 INFO       -  * Name: zh-CN
2024.10.04 23:42:22 INFO       -  * Display Name: <censored>
2024.10.04 23:42:22 INFO       -  * English Name: <censored>
2024.10.04 23:42:22 INFO       -  * 2-letter ISO Name: zh
2024.10.04 23:42:22 INFO       -  * 3-letter ISO Name: zho
2024.10.04 23:42:22 INFO       -  * 3-letter Win32 API Name: CHS
2024.10.04 23:42:22 INFO       -  Selecting language key: zh-CN
2024.10.04 23:42:22 LOG        -  [ToNStats] Setting destination: C:\Users\<censored>\AppData\Roaming\ToNSaveManager
2024.10.04 23:42:22 LOG        -  Reading from: C:\Users\<censored>\AppData\Roaming\ToNSaveManager\SaveIndex.json
2024.10.04 23:42:22 INFO       -  Entering Room Name: <censored>
2024.10.04 23:42:22 INFO       -  Instace [False] : <censored>
2024.10.04 23:42:22 INFO       -  Leaving instance...
<and other instance logs>
```

**Comment by inkuxuan** [comment]
Also, I need to know where my save data is saved. I probably need to copy it by hand so I get to continue with my savedata.

**Comment by ChrisFeline** [comment]
Have you tried deleting your VRChat logs?
It might be getting clustered with all the new logs.

Press Win + R
Then type: `%APPDATA%\..\LocalLow\VRChat\VRChat`

Delete every `.log` file in the folder.

**Comment by inkuxuan** [comment]
@ChrisFeline 
You are right. The last log file is 4.9GB and that is probably the reason.

**Comment by inkuxuan** [comment]
> 4.9GB !!!!!!!!!!!!!!!!!!!!!! ???????
@ChrisFeline Yes. I have filed an issue for VRChat.
https://feedback.vrchat.com/bug-reports/p/huge-log-file

**Comment by inkuxuan** [comment]
I'm gonna close this issue and leave it for VRChat.
=

**Comment by ChrisFeline** [comment]
Just as a side note. This is not a VRChat issue. - It's a world creator issue, logging is one of the most basic features of every application, without it you don't know what's happening, unfortunately some creators (sometimes unknowingly) leave errors in their worlds that get printed every frame and so it writes these messages over and over, so when a regular user comes to chill on these worlds for hours... the result is a huge log file over 5GB sometimes.

Just as a counter measure, in a future update I will try to detect these huge files, and inform the user with a popup that they are about to read a log that will cause the Save Manager to parse for a long period of time initially.
