### ISSUE TITLE
No Response

### ISSUE THREAD

**Issue by Liiiicht** [ChrisFeline/ToNSaveManager#56]
For around the past 2 weeks, I have been having massive issues with even launching the Tracker, it keeps going to "no response". Deleting it fully and reinstalling it didnt do anything. I am unsure how to properly launch it anymore :/ 

Sometimes just keeping it open for a while works, but not always

**Comment by ChrisFeline** [comment]
Try this: https://github.com/ChrisFeline/ToNSaveManager/issues/53#issuecomment-2394344697

**Comment by ChrisFeline** [comment]
I'll go ahead and close this issue now since the original user didn't respond.
