### ISSUE TITLE
ToN_ItemStatus does not Update

### ISSUE THREAD

**Issue by SCAbruh** [ChrisFeline/ToNSaveManager#72]
The osc parameter `ToN_ItemStatus` Does not update at all regardless of what item I use and what state it's in. I've tried it with the Rubber Mallet, TBH, and Paradise Lost, and I can't get it to ever read true. 
![2024-10-07 22_30_17-Window](https://github.com/user-attachments/assets/6adbaa6a-8a74-46cb-81de-77b2bd3aea3e)

**Comment by ChrisFeline** [comment]
Only works on the fun items that grant temporal speed.
Like TBH, Emerald Coil, Chaos Coil or Cork Screw.

This feature was something I asked beyond as a favor so I could detect it and send the parameters but it might be a bit inconsistent.

I've check and I forgot to add the lines for corkscrew and TBH, so those will be fixed next update.

**Comment by ChrisFeline** [comment]
Pushed an update referencing this issue.
