### ISSUE TITLE
Cant download updated version

### ISSUE THREAD

**Issue by XaiwakerSky** [ChrisFeline/ToNSaveManager#85]
![image](https://github.com/user-attachments/assets/c86d96d1-9b56-4e64-ba95-3849aa66246a)
I tried updating the software automatically when it said theres a new update available, but my pc came up with a virus warning, so i tried to install it manually and downloaded the latest version but it still wont let me use the application because it contains a virus or potentially unwanted software, like in the attached image
Can you assist please?

**Comment by ChrisFeline** [comment]
What Anti-Virus are you running?

**Comment by XaiwakerSky** [comment]
Microsoft defender that came installed with my pc when i bought it 8 years ago

**Comment by ChrisFeline** [comment]
Have you tried running it somewhere not in your Desktop folder?

**Comment by XaiwakerSky** [comment]
Tried it in a few different folders around my pc but it all gives the same result

**Comment by ChrisFeline** [comment]
You probably actually have one of this anti viruses: https://www.virustotal.com/gui/file/95baf56f981b12ae254d5ffd1ff1b639df57c4740fbb0e83d9129514e86cfd53?nocache=1

It doesn't mean the app has a virus, is just a false positive because of a recent change on it.
I might just roll back a version and see.

**Comment by ChrisFeline** [comment]
Just download a previous version

**Comment by XaiwakerSky** [comment]
i can no longer download a previous version as my pc still says theres a virus in the application, which is weird because it didnt say that when i downloaded it the first time

**Comment by ChrisFeline** [comment]
Try downloading this version, if it asks you to update just ignore it: https://github.com/ChrisFeline/ToNSaveManager/releases/tag/2024.10.8.976

**Comment by XaiwakerSky** [comment]
yep that one worked thanks

**Comment by ChrisFeline** [comment]
Whenever you have the chance, try downloading the artifact from: https://github.com/ChrisFeline/ToNSaveManager/actions/runs/11373242650

And tell me if it still does the issue.

**Comment by XaiwakerSky** [comment]
i will try this when i play again tomorrow

**Comment by XaiwakerSky** [comment]
Newest version works now
