### ISSUE TITLE
OSC parameters not resyncing with avatar reload

### ISSUE THREAD

**Issue by YOUNGBLOOD428** [ChrisFeline/ToNSaveManager#98]
When working with the OSC part of this, I've noticed that the parameters don't sync up when I reload the avatar, such as changing avatar, resetting the avatar, anything the forces a reload.

Namely the opted-in parameter has given me the most trouble. (Tho I suppose this applies to everything else, just that one doesn't update as frequently.)

So far my current workaround is to respawn to force the states to update.

**Comment by ChrisFeline** [comment]
This requires me to listen on a OSC port for avatar changing, I have no plans to do so at the moment. But for now, If you disable and enable the OSC feature in settings it re-sends the buffered parameters.

Reason: People use other apps that also listen on this port for avatar changes, like avatar protection tools or people with their "OSC Toys"
